<a href="https://colab.research.google.com/github/Riky2014/Tesi/blob/main/exact_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear

In [ ]:
import numpy as np
import sympy as sym

a_tilde = 1
K_tilde = 1 # 50e3
Pe_tilde = 0.0
m = 1 # 0.5
n = 0
rho = 1 # 1.05
K_r = 1 # 2.4160e-4

x, t = sym.symbols('x, t')
A_sym, q_sym = sym.symbols('A, q')

A = a_tilde + x - 3*t

q = 1 + x - 3*t

K = K_tilde

Pe = Pe_tilde

A0 = a_tilde

Psi = K * ((A_sym / A0) ** m - (A_sym / A0) ** n)

U = sym.Matrix([A, q])

In [ ]:
H = sym.Matrix([[0, 1], [A_sym / rho * sym.diff(Psi, A_sym) - (q_sym / A_sym) ** 2 , 2 * q_sym / A_sym]])
B = sym.Matrix([0, K_r * q_sym / A_sym])
C1 = sym.integrate(A_sym / rho * sym.diff(Psi, A_sym), (A_sym, A0, A_sym))
F = sym.Matrix([q_sym, q_sym ** 2/ A_sym + C1])
S = B
F = F.subs({A_sym: A, q_sym: q})
S = S.subs({A_sym: A, q_sym: q})

In [ ]:
H_np = np.array(H.subs({A_sym: 1.5, q_sym: 0.5}), dtype=float)

# Compute eigenvalues
eigenvalues = np.linalg.eigvals(H_np)
eigenvalues

array([-0.89141154,  1.5580782 ])

In [ ]:
dU_dt = sym.diff(U, t)
dF_dx = sym.diff(F, x)

dU_dt_dt = sym.diff(dU_dt, t)
dS_dt = sym.diff(S, t)
dF_dx_dt = sym.diff(dF_dx, t)

In [ ]:
dU_dt, dF_dx, S

(Matrix([
 [2*exp(2*t + 2*x)],
 [2*exp(2*t + 2*x)]]),
 Matrix([
 [                                        2*exp(2*t + 2*x)],
 [2*(exp(2*t + 2*x) + 1)*exp(2*t + 2*x) + 2*exp(2*t + 2*x)]]),
 Matrix([
 [0],
 [1]]))

In [ ]:
f = dU_dt + dF_dx + S
f

Matrix([
[                                            4*exp(2*t + 2*x)],
[2*(exp(2*t + 2*x) + 1)*exp(2*t + 2*x) + 4*exp(2*t + 2*x) + 1]])

In [ ]:
df_dt = sym.diff(f, t)
df_dt

Matrix([
[                                                                                                                                                                                                    1],
[2*t**3*x**3/(t*x + 1)**3 - 5*t**2*x**2/(t*x + 1)**2 - 0.0002416*t*x**2/(t*x + 1)**2 + 11904.7619047619*t*x/(t*x + 1)**0.5 + 4*t*x/(t*x + 1) + 0.0002416*x/(t*x + 1) + 23809.5238095238*(t*x + 1)**0.5]])

# Exponential

In [ ]:
import numpy as np
import sympy as sym

a_tilde = 1
K_tilde = 1 # 50e3
Pe_tilde = 0.0
m = 1 # 0.5
n = 0
rho = 1 # 1.05
K_r = 1 # 2.4160e-4

x, t = sym.symbols('x, t')
A_sym, q_sym = sym.symbols('A, q')

k = 1 #0.006
c = 1 #150
s = 1 #0
sigma = 1 #0.1

A = k * sym.exp(- (- x - c * t + s) ** 2 / sigma) + 1

q = k * c * sym.exp(- (- x - c * t + s) ** 2 / sigma)

K = K_tilde

Pe = Pe_tilde

A0 = a_tilde

Psi = K * ((A_sym / A0) ** m - (A_sym / A0) ** n)

U = sym.Matrix([A, q])

In [ ]:
H = sym.Matrix([[0, 1], [A_sym / rho * sym.diff(Psi, A_sym) - (q_sym / A_sym) ** 2 , 2 * q_sym / A_sym]])
B = sym.Matrix([0, K_r * q_sym / A_sym])
C1 = sym.integrate(A_sym / rho * sym.diff(Psi, A_sym), (A_sym, A0, A_sym))
F = sym.Matrix([q_sym, q_sym ** 2/ A_sym + C1])
S = B
F = F.subs({A_sym: A, q_sym: q})
S = S.subs({A_sym: A, q_sym: q})

In [ ]:
H_np = np.array(H.subs({A_sym: 1.5, q_sym: 0.5}), dtype=float)

# Compute eigenvalues
eigenvalues = np.linalg.eigvals(H_np)
eigenvalues

array([-0.89141154,  1.5580782 ])

In [ ]:
dU_dt = sym.diff(U, t)
dF_dx = sym.diff(F, x)

dU_dt_dt = sym.diff(dU_dt, t)
dS_dt = sym.diff(S, t)
dF_dx_dt = sym.diff(dF_dx, t)

In [ ]:
f = dU_dt + dF_dx + S
f

Matrix([
[                                                                                                                                                                                                                                                                        2*(-2*t - 2*x + 2)*exp(-(-t - x + 1)**2)],
[(1 + exp(-(-t - x + 1)**2))*(-2*t - 2*x + 2)*exp(-(-t - x + 1)**2) + (-2*t - 2*x + 2)*exp(-(-t - x + 1)**2) + (-4*t - 4*x + 4)*exp(-2*(-t - x + 1)**2)/(1 + exp(-(-t - x + 1)**2)) + exp(-(-t - x + 1)**2)/(1 + exp(-(-t - x + 1)**2)) - (-2*t - 2*x + 2)*exp(-3*(-t - x + 1)**2)/(1 + exp(-(-t - x + 1)**2))**2]])

In [ ]:
df_dt = sym.diff(f, t)
df_dt

Matrix([
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           2*(-2*t - 2*x + 2)**2*exp(-(-t - x + 1)**2) - 4*exp(-(-t - x + 1)**2)],
[(1 + exp(-(-t - x + 1)**2))*(-2*t - 2*x + 2)**2*exp(-(-t - x + 1)**2) - 2*(1 + exp(-(-t - x + 1)**2))*exp(-(-t - x + 1)**2) + (-2*t - 2*x + 2)**2*exp(-(-t

# Sinusoidal

In [61]:
import numpy as np
import sympy as sym

L = 1
T = 1
A_tilde = 4
a_tilde = 4e-1
q_tilde = 0.0
K_tilde = 50e4
Pe_tilde = 0.0
m = 0.5
n = 0
rho = 1.050
K_r = 2.4160

x, t = sym.symbols('x, t')
A_sym, q_sym = sym.symbols('A, q')

A = A_tilde + a_tilde * sym.sin(2 * np.pi / L * x) * sym.cos(2 * np.pi / T * t)

q = q_tilde - (a_tilde * L / T) * sym.cos(2 * np.pi / L * x) * sym.sin(2 * np.pi / T * t)

K = K_tilde

Pe = Pe_tilde

A0 = A_tilde

Psi = K * ((A_sym / A0) ** m - (A_sym / A0) ** n)

U = sym.Matrix([A, q])

In [62]:
H = sym.Matrix([[0, 1], [A_sym / rho * sym.diff(Psi, A_sym) - (q_sym / A_sym) ** 2 , 2 * q_sym / A_sym]])
B = sym.Matrix([0, K_r * q_sym / A_sym])
C1 = sym.integrate(A_sym / rho * sym.diff(Psi, A_sym), (A_sym, A0, A_sym))
F = sym.Matrix([q_sym, q_sym ** 2/ A_sym + C1])
S = B
F = F.subs({A_sym: A, q_sym: q})
S = S.subs({A_sym: A, q_sym: q})

In [63]:
H

Matrix([
[                                  0,     1],
[119047.619047619*A**0.5 - q**2/A**2, 2*q/A]])

In [64]:
H_np = np.array(H.subs({A_sym: A_tilde, q_sym: q_tilde}), dtype=float)

# Compute eigenvalues
eigenvalues = np.linalg.eigvals(H_np)
eigenvalues

array([ 487.95003647, -487.95003647])

In [54]:
dU_dt = sym.diff(U, t)
dF_dx = sym.diff(F, x)

dU_dt_dt = sym.diff(dU_dt, t)
dS_dt = sym.diff(S, t)
dF_dx_dt = sym.diff(dF_dx, t)

In [55]:
f = dU_dt + dF_dx + S
f

Matrix([
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        0],
[0.0059839860068377*(0.1*sin(6.28318530717959*x)*cos(6.28318530717959*t) + 1)**0.5*cos(6.28318530717959*t)*cos(6.28318530717959*x) - 0.000251327412287183*cos(6.28318530717959*t)*cos(6.28318530717959*x) - 2.51327412287184e-6*sin(6.28318530717959*t)**2*cos(6.28318530717959*t)*cos(6.28318530717959*x)**3/(0.1*sin(6.28318530717959*x)*cos(6.2

In [56]:
df_dt = sym.diff(f, t)
df_dt

Matrix([
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              